# Generated by Django 5.2.5 on 2025-08-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_inspiration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='category',
            field=models.CharField(choices=[('motivation', 'Motivation and Life Wisdom'), ('love', 'Love & Relationships'), ('faith', 'Faith & Religion')], max_length=50),
        ),
    ]
